name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v services/vreco/...

    - name: Run go vet
      run: go vet services/vreco/...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.2

    - name: Run staticcheck
      run: staticcheck services/vreco/...

    - name: Run tests
      run: go test -race -vet=off services/vreco/...
