name: Vreco Test

on:
  push:
    branches: [main]
    paths:
      - 'services/vreco**/*'
  pull_request:
    branches: [main]
    paths:
      - 'services/vreco**/*'    

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~\AppData\Local\go-build
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
      ${{ runner.os }}-go-${{ matrix.go-version }}-    

    - name: Verify dependencies vreco
      run: cd services/vreco && go mod verify

    - name: Build
      run: go build -v services/vreco/...

    - name: Run go vet
      run: go vet services/vreco/...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.2

    - name: Run staticcheck
      run: staticcheck services/vreco/...

    - name: Run tests
      run: go test -race -vet=off services/vreco/...
